[package]
name = "ternop"
version = "1.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
description= "A tiny macro that implements a ternary operator for Rust"
license = "MIT/X11"
keywords = ["ternary", "operator", "inline if", "if"]
documentation = "https://docs.rs/ternop/1.0.0/ternop/"